# Generated by Django 6.1.1 on 2026-09-21 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notificaciones", models.BooleanField(default=True)),
                ("radio_km", models.FloatField(default=5)),
                ("anonimo_por_defecto", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("bloqueo", "Bloqueo"),
                            ("protesta", "Protesta"),
                            ("incendio", "Incendio"),
                            ("agresion", "Agresión"),
                            ("vandalismo", "Vandalismo"),
                            ("desaparecida", "Persona desaparecida"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("lugar", models.CharField(max_length=160)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("creado_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonimo", models.BooleanField(default=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="reportes/"),
                ),
                ("severidad", models.PositiveSmallIntegerField(default=3)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Validacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirma", models.BooleanField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validaciones",
                        to="api.reporte",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusquedaReciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=160)),
                ("creado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="busquedas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "texto"), name="busqueda_unica_por_usuario"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["lat", "lng"], name="api_reporte_lat_0a626e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["tipo", "creado_en"], name="api_reporte_tipo_9b4406_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="validacion",
            constraint=models.UniqueConstraint(
                fields=("reporte", "usuario"), name="una_validacion_por_usuario"
            ),
        ),
    ]
